name: StayEasy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: jest
          POSTGRES_PASSWORD: jest
          POSTGRES_DB: stayeasy_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Prisma Generate
      run: npx prisma generate

    - name: Run Migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

    - name: Run Lint
      run: npm run lint

    - name: Run Typecheck
      run: npm run typecheck

    - name: Run Tests
      run: npm run test:ci
      env:
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        JWT_SECRET: test-secret